### ISSUE TITLE
Remove `Generics.Console.GetOpt.Generics` [breaking change]

### ISSUE THREAD

**Issue by soenkehahn** [zalora/getopt-generics#52]
I'm thinking of removing `Generics.Console.GetOpt.Generics` althogether. And `getArguments` too. That would make `WithCli.withCli` the only interface (and `withCliModified`), but those are more powerful and I think we should only have one way. This is quite a breaking change, that's why I'm asking whether there's any objections.

(The name `getopt-generics` seems a bit arbitrary then, but, well, one step at a time.)

cc: @sol @tuleism @proger @qoelet @dmjio @phunehehe

**Comment by phunehehe** [comment]
This will probably break some stuff I wrote but those aren't very important and having one way is something to strive for anyway. No objection from me.

**Comment by sol** [comment]
I recently imagined a use case where it would be useful and I started to appreciate your initial approach.  But (1) I didn't try anything (2) I guess it's always possible to work around with `withArgs` (3) if you are confident about the changes, go for it.

**Comment by soenkehahn** [comment]
@sol: What aspect of the initial approach are you talking about? That it wasn't a `with...`-style type signature? Or that we had a pure variant of the interface?

I hoped that everything that was possible with `getArguments` is still doable with `withCli`, except for the pure interface (that I intend to add back in).

**Comment by dmjio** [comment]
@soenkehahn, this is fine with me.

**Comment by soenkehahn** [comment]
Released as `0.13`.
