### ISSUE TITLE
Get rid of generics-sop dependency

### ISSUE THREAD

**Issue by sol** [zalora/getopt-generics#7]
@soenkehahn [`Data.Aeson.genericParseJSON`](http://hackage.haskell.org/package/aeson-0.8.0.2/docs/Data-Aeson.html#v:genericParseJSON) requires `FromJSON` instances for all field names without depending on `generics-sop`.  Could we do something similar?

**Comment by soenkehahn** [comment]
Yes, it looks like this could be done. But it would be much more complicated. I won't be working on this soon.

**Comment by sol** [comment]
Fine for me to close as won't fix ;)
